"""split outbox lock owner and token

Revision ID: 0d341554cdf1
Revises: cb523e9a0eb4
Create Date: 2026-07-22 11:12:07.444902
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = "0d341554cdf1"
down_revision: str | Sequence[str] | None = "cb523e9a0eb4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply the schema change."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("outbox_events", sa.Column("lock_owner", sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert the schema change."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("outbox_events", "lock_owner")
    # ### end Alembic commands ###
