"""phase1 durable runtime

Revision ID: cb523e9a0eb4
Revises:
Create Date: 2026-07-22 10:30:14.566792
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

revision: str = "cb523e9a0eb4"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply the schema change."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agent_checkpoint_writes",
        sa.Column("thread_id", sa.String(length=128), nullable=False),
        sa.Column("checkpoint_namespace", sa.String(length=256), nullable=False),
        sa.Column("checkpoint_id", sa.String(length=64), nullable=False),
        sa.Column("task_id", sa.String(length=128), nullable=False),
        sa.Column("write_index", sa.Integer(), nullable=False),
        sa.Column("task_path", sa.String(length=512), nullable=False),
        sa.Column("channel", sa.String(length=256), nullable=False),
        sa.Column("value_type", sa.String(length=64), nullable=False),
        sa.Column("value_blob", sa.LargeBinary(length=16777215), nullable=False),
        sa.Column("created_at", mysql.DATETIME(fsp=0), nullable=False),
        sa.PrimaryKeyConstraint(
            "thread_id", "checkpoint_namespace", "checkpoint_id", "task_id", "write_index"
        ),
        mysql_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_index(
        "ix_checkpoint_writes_checkpoint",
        "agent_checkpoint_writes",
        ["thread_id", "checkpoint_namespace", "checkpoint_id"],
        unique=False,
    )
    op.create_table(
        "agent_checkpoints",
        sa.Column("thread_id", sa.String(length=128), nullable=False),
        sa.Column("checkpoint_namespace", sa.String(length=256), nullable=False),
        sa.Column("checkpoint_id", sa.String(length=64), nullable=False),
        sa.Column("parent_checkpoint_id", sa.String(length=64), nullable=True),
        sa.Column("workflow_id", sa.String(length=36), nullable=True),
        sa.Column("workflow_version", sa.Integer(), nullable=True),
        sa.Column("run_id", sa.String(length=64), nullable=True),
        sa.Column("checkpoint_type", sa.String(length=64), nullable=False),
        sa.Column("checkpoint_blob", sa.LargeBinary(length=16777215), nullable=False),
        sa.Column("metadata_type", sa.String(length=64), nullable=False),
        sa.Column("metadata_blob", sa.LargeBinary(length=16777215), nullable=False),
        sa.Column("metadata_json", sa.JSON(), nullable=False),
        sa.Column("created_at", mysql.DATETIME(fsp=0), nullable=False),
        sa.Column("expires_at", mysql.DATETIME(fsp=0), nullable=True),
        sa.PrimaryKeyConstraint("thread_id", "checkpoint_namespace", "checkpoint_id"),
        mysql_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_index(
        "ix_agent_checkpoints_expires", "agent_checkpoints", ["expires_at"], unique=False
    )
    op.create_index(
        "ix_agent_checkpoints_latest",
        "agent_checkpoints",
        ["thread_id", "checkpoint_namespace", "checkpoint_id"],
        unique=False,
    )
    op.create_index("ix_agent_checkpoints_run", "agent_checkpoints", ["run_id"], unique=False)
    op.create_table(
        "audit_events",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("workspace_id", sa.String(length=128), nullable=False),
        sa.Column("actor_type", sa.String(length=32), nullable=False),
        sa.Column("actor_id", sa.String(length=128), nullable=False),
        sa.Column("action", sa.String(length=128), nullable=False),
        sa.Column("resource_type", sa.String(length=64), nullable=False),
        sa.Column("resource_id", sa.String(length=128), nullable=False),
        sa.Column("trace_id", sa.String(length=64), nullable=False),
        sa.Column("metadata_json", sa.JSON(), nullable=False),
        sa.Column("created_at", mysql.DATETIME(fsp=0), nullable=False),
        sa.Column("expires_at", mysql.DATETIME(fsp=0), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        mysql_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_index("ix_audit_expires", "audit_events", ["expires_at"], unique=False)
    op.create_index(
        "ix_audit_resource",
        "audit_events",
        ["resource_type", "resource_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "dead_letter_messages",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("consumer", sa.String(length=128), nullable=False),
        sa.Column("message_id", sa.String(length=128), nullable=False),
        sa.Column("event_type", sa.String(length=128), nullable=False),
        sa.Column("payload_json", sa.JSON(), nullable=False),
        sa.Column("reason", sa.String(length=256), nullable=False),
        sa.Column("error_class", sa.String(length=160), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column(
            "original_created_at", mysql.DATETIME(fsp=0), nullable=False
        ),
        sa.Column("created_at", mysql.DATETIME(fsp=0), nullable=False),
        sa.Column("replayed_at", mysql.DATETIME(fsp=0), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("consumer", "message_id", name="uq_dead_letter_message"),
        mysql_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_index("ix_dead_letter_created", "dead_letter_messages", ["created_at"], unique=False)
    op.create_table(
        "idempotency_keys",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("scope", sa.String(length=160), nullable=False),
        sa.Column("key_hash", sa.String(length=64), nullable=False),
        sa.Column("request_hash", sa.String(length=64), nullable=False),
        sa.Column("resource_type", sa.String(length=64), nullable=False),
        sa.Column("resource_id", sa.String(length=128), nullable=False),
        sa.Column("response_json", sa.JSON(), nullable=True),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("created_at", mysql.DATETIME(fsp=0), nullable=False),
        sa.Column("expires_at", mysql.DATETIME(fsp=0), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("scope", "key_hash", name="uq_idempotency_scope_key"),
        mysql_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_index("ix_idempotency_expires", "idempotency_keys", ["expires_at"], unique=False)
    op.create_table(
        "inbox_messages",
        sa.Column("consumer", sa.String(length=128), nullable=False),
        sa.Column("message_id", sa.String(length=128), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("lease_owner", sa.String(length=128), nullable=True),
        sa.Column("lease_token", sa.String(length=36), nullable=True),
        sa.Column(
            "lease_expires_at", mysql.DATETIME(fsp=0), nullable=True
        ),
        sa.Column("delivery_attempts", sa.Integer(), nullable=False),
        sa.Column("processed_at", mysql.DATETIME(fsp=0), nullable=True),
        sa.Column("error_class", sa.String(length=160), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("created_at", mysql.DATETIME(fsp=0), nullable=False),
        sa.Column("updated_at", mysql.DATETIME(fsp=0), nullable=False),
        sa.PrimaryKeyConstraint("consumer", "message_id"),
        mysql_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_index(
        "ix_inbox_lease", "inbox_messages", ["status", "lease_expires_at"], unique=False
    )
    op.create_table(
        "outbox_events",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("aggregate_type", sa.String(length=64), nullable=False),
        sa.Column("aggregate_id", sa.String(length=128), nullable=False),
        sa.Column("event_type", sa.String(length=128), nullable=False),
        sa.Column("schema_version", sa.Integer(), nullable=False),
        sa.Column("aggregate_version", sa.Integer(), nullable=False),
        sa.Column("trace_id", sa.String(length=64), nullable=False),
        sa.Column("payload_json", sa.JSON(), nullable=False),
        sa.Column("occurred_at", mysql.DATETIME(fsp=0), nullable=False),
        sa.Column("available_at", mysql.DATETIME(fsp=0), nullable=False),
        sa.Column("published_at", mysql.DATETIME(fsp=0), nullable=True),
        sa.Column("publish_attempts", sa.Integer(), nullable=False),
        sa.Column("lock_token", sa.String(length=36), nullable=True),
        sa.Column("locked_until", mysql.DATETIME(fsp=0), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        mysql_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_index(
        "ix_outbox_aggregate",
        "outbox_events",
        ["aggregate_type", "aggregate_id", "occurred_at"],
        unique=False,
    )
    op.create_index(
        "ix_outbox_ready",
        "outbox_events",
        ["published_at", "available_at", "locked_until"],
        unique=False,
    )
    op.create_table(
        "workflows",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("workspace_id", sa.String(length=128), nullable=False),
        sa.Column("created_by", sa.String(length=128), nullable=False),
        sa.Column("workflow_type", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("retention_status", sa.String(length=24), nullable=False),
        sa.Column("current_node", sa.String(length=128), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("input_json", sa.JSON(), nullable=False),
        sa.Column("result_json", sa.JSON(), nullable=True),
        sa.Column("expires_at", mysql.DATETIME(fsp=0), nullable=False),
        sa.Column(
            "cancellation_requested_at",
            mysql.DATETIME(fsp=0),
            nullable=True,
        ),
        sa.Column("created_at", mysql.DATETIME(fsp=0), nullable=False),
        sa.Column("updated_at", mysql.DATETIME(fsp=0), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        mysql_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_index(
        "ix_workflows_retention_expires",
        "workflows",
        ["retention_status", "expires_at"],
        unique=False,
    )
    op.create_index(
        "ix_workflows_status_updated", "workflows", ["status", "updated_at"], unique=False
    )
    op.create_index(
        "ix_workflows_workspace_created",
        "workflows",
        ["workspace_id", "created_at", "id"],
        unique=False,
    )
    op.create_table(
        "workflow_approvals",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("workflow_id", sa.String(length=36), nullable=False),
        sa.Column("approval_type", sa.String(length=32), nullable=False),
        sa.Column("subject_id", sa.String(length=128), nullable=False),
        sa.Column("subject_version", sa.Integer(), nullable=False),
        sa.Column("decision", sa.String(length=24), nullable=False),
        sa.Column("reason_code", sa.String(length=128), nullable=True),
        sa.Column("comment_ref", sa.String(length=512), nullable=True),
        sa.Column("approved_by", sa.String(length=128), nullable=False),
        sa.Column("expected_workflow_version", sa.Integer(), nullable=False),
        sa.Column("created_at", mysql.DATETIME(fsp=0), nullable=False),
        sa.ForeignKeyConstraint(["workflow_id"], ["workflows.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "workflow_id",
            "approval_type",
            "subject_id",
            "subject_version",
            "decision",
            "expected_workflow_version",
            name="uq_workflow_approvals_replay",
        ),
        mysql_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_index(
        "ix_workflow_approvals_workflow",
        "workflow_approvals",
        ["workflow_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "workflow_steps",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("workflow_id", sa.String(length=36), nullable=False),
        sa.Column("step_key", sa.String(length=160), nullable=False),
        sa.Column("step_type", sa.String(length=48), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("expected_workflow_version", sa.Integer(), nullable=False),
        sa.Column("lease_owner", sa.String(length=128), nullable=True),
        sa.Column("lease_token", sa.String(length=36), nullable=True),
        sa.Column(
            "lease_expires_at", mysql.DATETIME(fsp=0), nullable=True
        ),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("max_attempts", sa.Integer(), nullable=False),
        sa.Column(
            "next_attempt_at", mysql.DATETIME(fsp=0), nullable=True
        ),
        sa.Column("input_ref", sa.String(length=512), nullable=True),
        sa.Column("output_ref", sa.String(length=512), nullable=True),
        sa.Column("input_json", sa.JSON(), nullable=True),
        sa.Column("output_json", sa.JSON(), nullable=True),
        sa.Column("error_class", sa.String(length=160), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("started_at", mysql.DATETIME(fsp=0), nullable=True),
        sa.Column("completed_at", mysql.DATETIME(fsp=0), nullable=True),
        sa.Column("created_at", mysql.DATETIME(fsp=0), nullable=False),
        sa.Column("updated_at", mysql.DATETIME(fsp=0), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["workflow_id"], ["workflows.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("workflow_id", "step_key", name="uq_workflow_steps_key"),
        mysql_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_index(
        "ix_workflow_steps_lease", "workflow_steps", ["status", "lease_expires_at"], unique=False
    )
    op.create_index(
        "ix_workflow_steps_retry", "workflow_steps", ["status", "next_attempt_at"], unique=False
    )
    op.create_index(
        "ix_workflow_steps_workflow_sequence",
        "workflow_steps",
        ["workflow_id", "sequence"],
        unique=False,
    )
    op.create_table(
        "workflow_attempts",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("workflow_id", sa.String(length=36), nullable=False),
        sa.Column("step_id", sa.String(length=36), nullable=False),
        sa.Column("attempt_number", sa.Integer(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("provider_request_id", sa.String(length=256), nullable=True),
        sa.Column("request_ref", sa.String(length=512), nullable=True),
        sa.Column("result_ref", sa.String(length=512), nullable=True),
        sa.Column("request_json", sa.JSON(), nullable=True),
        sa.Column("result_json", sa.JSON(), nullable=True),
        sa.Column("error_class", sa.String(length=160), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("created_at", mysql.DATETIME(fsp=0), nullable=False),
        sa.Column("updated_at", mysql.DATETIME(fsp=0), nullable=False),
        sa.Column("started_at", mysql.DATETIME(fsp=0), nullable=True),
        sa.Column("completed_at", mysql.DATETIME(fsp=0), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["step_id"], ["workflow_steps.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["workflow_id"], ["workflows.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("idempotency_key", name="uq_workflow_attempts_idempotency"),
        sa.UniqueConstraint("step_id", "attempt_number", name="uq_workflow_attempts_number"),
        mysql_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_index(
        "ix_workflow_attempts_status", "workflow_attempts", ["status", "updated_at"], unique=False
    )
    op.create_index(
        "ix_workflow_attempts_workflow",
        "workflow_attempts",
        ["workflow_id", "created_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert the schema change."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_workflow_attempts_workflow", table_name="workflow_attempts")
    op.drop_index("ix_workflow_attempts_status", table_name="workflow_attempts")
    op.drop_table("workflow_attempts")
    op.drop_index("ix_workflow_steps_workflow_sequence", table_name="workflow_steps")
    op.drop_index("ix_workflow_steps_retry", table_name="workflow_steps")
    op.drop_index("ix_workflow_steps_lease", table_name="workflow_steps")
    op.drop_table("workflow_steps")
    op.drop_index("ix_workflow_approvals_workflow", table_name="workflow_approvals")
    op.drop_table("workflow_approvals")
    op.drop_index("ix_workflows_workspace_created", table_name="workflows")
    op.drop_index("ix_workflows_status_updated", table_name="workflows")
    op.drop_index("ix_workflows_retention_expires", table_name="workflows")
    op.drop_table("workflows")
    op.drop_index("ix_outbox_ready", table_name="outbox_events")
    op.drop_index("ix_outbox_aggregate", table_name="outbox_events")
    op.drop_table("outbox_events")
    op.drop_index("ix_inbox_lease", table_name="inbox_messages")
    op.drop_table("inbox_messages")
    op.drop_index("ix_idempotency_expires", table_name="idempotency_keys")
    op.drop_table("idempotency_keys")
    op.drop_index("ix_dead_letter_created", table_name="dead_letter_messages")
    op.drop_table("dead_letter_messages")
    op.drop_index("ix_audit_resource", table_name="audit_events")
    op.drop_index("ix_audit_expires", table_name="audit_events")
    op.drop_table("audit_events")
    op.drop_index("ix_agent_checkpoints_run", table_name="agent_checkpoints")
    op.drop_index("ix_agent_checkpoints_latest", table_name="agent_checkpoints")
    op.drop_index("ix_agent_checkpoints_expires", table_name="agent_checkpoints")
    op.drop_table("agent_checkpoints")
    op.drop_index("ix_checkpoint_writes_checkpoint", table_name="agent_checkpoint_writes")
    op.drop_table("agent_checkpoint_writes")
    # ### end Alembic commands ###
