"""product brief analysis and confirmation

Revision ID: d9e4f7a2b610
Revises: c8d3e7f1a602
Create Date: 2026-07-28 10:07:25.771624
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

revision: str = "d9e4f7a2b610"
down_revision: str | Sequence[str] | None = "c8d3e7f1a602"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

_WORKSPACE = sa.String(128, collation="utf8mb4_0900_bin")
_IMMUTABLE_HISTORY_TABLES = (
    "product_brief_analysis_requests",
    "product_brief_source_assets",
    "product_brief_provider_attempts",
    "product_brief_provider_calls",
    "product_brief_versions",
    "product_brief_fields",
    "product_brief_evidence",
    "product_brief_confirmations",
)
_DELETE_PROTECTED_TABLES = ("product_briefs", *_IMMUTABLE_HISTORY_TABLES)


def upgrade() -> None:
    """Apply the schema change."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "product_briefs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("workspace_id", _WORKSPACE, nullable=False),
        sa.Column("workflow_id", sa.String(length=36), nullable=False),
        sa.Column("product_id", sa.String(length=36), nullable=False),
        sa.Column("operation_id", sa.String(length=36), nullable=False),
        sa.Column("created_by", sa.String(length=128), nullable=False),
        sa.Column("state", sa.String(length=32), nullable=False),
        sa.Column("current_version_id", sa.String(length=36), nullable=True),
        sa.Column("confirmed_version_id", sa.String(length=36), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("retention_class", sa.String(length=16), nullable=False),
        sa.Column("retention_deadline", mysql.DATETIME(fsp=6), nullable=True),
        sa.Column("created_at", mysql.DATETIME(fsp=6), nullable=False),
        sa.Column("updated_at", mysql.DATETIME(fsp=6), nullable=False),
        sa.CheckConstraint(
            "(retention_class = 'TASK' AND retention_deadline IS NOT NULL) "
            "OR (retention_class = 'FOUNDATION' AND retention_deadline IS NULL)",
            name="ck_product_briefs_retention",
        ),
        sa.CheckConstraint(
            "state IN ('DRAFT', 'AWAITING_CONFIRMATION', 'CONFIRMED', 'ARCHIVED')",
            name="ck_product_briefs_state",
        ),
        sa.CheckConstraint("version > 0", name="ck_product_briefs_version"),
        sa.ForeignKeyConstraint(
            ["workspace_id", "confirmed_version_id", "id"],
            [
                "product_brief_versions.workspace_id",
                "product_brief_versions.id",
                "product_brief_versions.product_brief_id",
            ],
            name="fk_product_briefs_confirmed_version",
            ondelete="RESTRICT",
            use_alter=True,
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "current_version_id", "id"],
            [
                "product_brief_versions.workspace_id",
                "product_brief_versions.id",
                "product_brief_versions.product_brief_id",
            ],
            name="fk_product_briefs_current_version",
            ondelete="RESTRICT",
            use_alter=True,
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "operation_id"],
            ["durable_operations.workspace_id", "durable_operations.id"],
            name="fk_product_briefs_workspace_operation",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "product_id"],
            ["products.workspace_id", "products.id"],
            name="fk_product_briefs_workspace_product",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "workflow_id"],
            ["workflows.workspace_id", "workflows.id"],
            name="fk_product_briefs_workspace_workflow",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("operation_id"),
        sa.UniqueConstraint("workspace_id", "id", name="uq_product_briefs_workspace_id"),
        sa.UniqueConstraint(
            "workspace_id", "workflow_id", "product_id", name="uq_product_briefs_workflow_product"
        ),
        mysql_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_index(
        "ix_product_briefs_retention",
        "product_briefs",
        ["retention_class", "retention_deadline", "state"],
        unique=False,
    )
    op.create_index(
        "ix_product_briefs_workspace_updated",
        "product_briefs",
        ["workspace_id", "updated_at", "id"],
        unique=False,
    )
    op.create_table(
        "product_brief_analysis_requests",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("workspace_id", _WORKSPACE, nullable=False),
        sa.Column("product_brief_id", sa.String(length=36), nullable=False),
        sa.Column("operation_id", sa.String(length=36), nullable=False),
        sa.Column("category", sa.String(length=32), nullable=False),
        sa.Column("expected_workflow_version", sa.Integer(), nullable=False),
        sa.Column("product_catalog_version", sa.Integer(), nullable=False),
        sa.Column("provider", sa.String(length=64), nullable=False),
        sa.Column("endpoint_region", sa.String(length=64), nullable=False),
        sa.Column(
            "endpoint_host", sa.String(length=255, collation="utf8mb4_0900_bin"), nullable=False
        ),
        sa.Column("requested_model", sa.String(length=128), nullable=False),
        sa.Column("submitted_model_snapshot", sa.String(length=128), nullable=False),
        sa.Column(
            "provider_configuration_snapshot_sha256",
            sa.String(length=64, collation="utf8mb4_0900_bin"),
            nullable=False,
        ),
        sa.Column("prompt_version", sa.String(length=64), nullable=False),
        sa.Column("review_policy_version", sa.String(length=64), nullable=False),
        sa.Column("review_confidence_threshold", sa.Numeric(5, 4), nullable=False),
        sa.Column("review_mandatory_paths_json", sa.JSON(), nullable=False),
        sa.Column("review_sensitive_claim_paths_json", sa.JSON(), nullable=False),
        sa.Column(
            "review_policy_snapshot_sha256",
            sa.String(length=64, collation="utf8mb4_0900_bin"),
            nullable=False,
        ),
        sa.Column("transfer_policy_version", sa.String(length=64), nullable=False),
        sa.Column(
            "transfer_policy_snapshot_sha256",
            sa.String(length=64, collation="utf8mb4_0900_bin"),
            nullable=False,
        ),
        sa.Column("created_by", sa.String(length=128), nullable=False),
        sa.Column("retention_class", sa.String(length=16), nullable=False),
        sa.Column("retention_deadline", mysql.DATETIME(fsp=6), nullable=True),
        sa.Column("created_at", mysql.DATETIME(fsp=6), nullable=False),
        sa.CheckConstraint(
            "(retention_class = 'TASK' AND retention_deadline IS NOT NULL) "
            "OR (retention_class = 'FOUNDATION' AND retention_deadline IS NULL)",
            name="ck_product_brief_analysis_requests_retention",
        ),
        sa.CheckConstraint(
            "category IN ('BEAUTY', 'AUTOMOTIVE')",
            name="ck_product_brief_analysis_requests_category",
        ),
        sa.CheckConstraint(
            "transfer_policy_snapshot_sha256 REGEXP '^[0-9a-f]{64}$'",
            name="ck_product_brief_analysis_requests_transfer_snapshot",
        ),
        sa.CheckConstraint(
            "provider_configuration_snapshot_sha256 REGEXP '^[0-9a-f]{64}$'",
            name="ck_product_brief_analysis_requests_provider_snapshot",
        ),
        sa.CheckConstraint(
            "review_policy_snapshot_sha256 REGEXP '^[0-9a-f]{64}$'",
            name="ck_product_brief_analysis_requests_review_snapshot",
        ),
        sa.CheckConstraint(
            "review_confidence_threshold >= 0 AND review_confidence_threshold <= 1",
            name="ck_product_brief_analysis_requests_confidence",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "operation_id"],
            ["durable_operations.workspace_id", "durable_operations.id"],
            name="fk_product_brief_analysis_requests_operation",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "product_brief_id"],
            ["product_briefs.workspace_id", "product_briefs.id"],
            name="fk_product_brief_analysis_requests_brief",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "workspace_id", "id", name="uq_product_brief_analysis_requests_workspace_id"
        ),
        sa.UniqueConstraint(
            "workspace_id", "operation_id", name="uq_product_brief_analysis_requests_operation"
        ),
        mysql_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_index(
        "ix_product_brief_analysis_requests_brief_created",
        "product_brief_analysis_requests",
        ["workspace_id", "product_brief_id", "created_at", "id"],
        unique=False,
    )
    op.create_index(
        "ix_product_brief_analysis_requests_workspace_created",
        "product_brief_analysis_requests",
        ["workspace_id", "created_at", "id"],
        unique=False,
    )
    op.create_table(
        "product_brief_provider_attempts",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("workspace_id", _WORKSPACE, nullable=False),
        sa.Column("product_brief_id", sa.String(length=36), nullable=False),
        sa.Column("operation_id", sa.String(length=36), nullable=False),
        sa.Column("operation_attempt", sa.Integer(), nullable=False),
        sa.Column("call_index", sa.Integer(), nullable=False),
        sa.Column(
            "submission_key_sha256",
            sa.String(length=64, collation="utf8mb4_0900_bin"),
            nullable=False,
        ),
        sa.Column(
            "input_sha256",
            sa.String(length=64, collation="utf8mb4_0900_bin"),
            nullable=False,
        ),
        sa.Column("provider", sa.String(length=64), nullable=False),
        sa.Column("endpoint_region", sa.String(length=64), nullable=False),
        sa.Column(
            "endpoint_host",
            sa.String(length=255, collation="utf8mb4_0900_bin"),
            nullable=False,
        ),
        sa.Column("requested_model", sa.String(length=128), nullable=False),
        sa.Column("submitted_model_snapshot", sa.String(length=128), nullable=False),
        sa.Column("prompt_version", sa.String(length=64), nullable=False),
        sa.Column(
            "config_snapshot_sha256",
            sa.String(length=64, collation="utf8mb4_0900_bin"),
            nullable=False,
        ),
        sa.Column("retention_class", sa.String(length=16), nullable=False),
        sa.Column("retention_deadline", mysql.DATETIME(fsp=6), nullable=True),
        sa.Column("created_at", mysql.DATETIME(fsp=6), nullable=False),
        sa.CheckConstraint(
            "operation_attempt > 0 AND call_index >= 0",
            name="ck_product_brief_provider_attempts_number",
        ),
        sa.CheckConstraint(
            "submission_key_sha256 REGEXP '^[0-9a-f]{64}$' "
            "AND input_sha256 REGEXP '^[0-9a-f]{64}$' "
            "AND config_snapshot_sha256 REGEXP '^[0-9a-f]{64}$'",
            name="ck_product_brief_provider_attempts_hashes",
        ),
        sa.CheckConstraint(
            "(retention_class = 'TASK' AND retention_deadline IS NOT NULL) "
            "OR (retention_class = 'FOUNDATION' AND retention_deadline IS NULL)",
            name="ck_product_brief_provider_attempts_retention",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "operation_id"],
            ["durable_operations.workspace_id", "durable_operations.id"],
            name="fk_product_brief_provider_attempts_operation",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "product_brief_id"],
            ["product_briefs.workspace_id", "product_briefs.id"],
            name="fk_product_brief_provider_attempts_brief",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "operation_id",
            "operation_attempt",
            "call_index",
            name="uq_product_brief_provider_attempts_operation",
        ),
        sa.UniqueConstraint(
            "workspace_id",
            "id",
            name="uq_product_brief_provider_attempts_workspace_id",
        ),
        mysql_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_index(
        "ix_product_brief_provider_attempts_brief_created",
        "product_brief_provider_attempts",
        ["workspace_id", "product_brief_id", "created_at", "id"],
        unique=False,
    )
    op.create_table(
        "product_brief_provider_calls",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("workspace_id", _WORKSPACE, nullable=False),
        sa.Column("product_brief_id", sa.String(length=36), nullable=False),
        sa.Column("operation_id", sa.String(length=36), nullable=False),
        sa.Column("operation_attempt", sa.Integer(), nullable=False),
        sa.Column("call_index", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("provider", sa.String(length=64), nullable=False),
        sa.Column("endpoint_region", sa.String(length=64), nullable=False),
        sa.Column(
            "endpoint_host", sa.String(length=255, collation="utf8mb4_0900_bin"), nullable=False
        ),
        sa.Column("requested_model", sa.String(length=128), nullable=False),
        sa.Column("submitted_model_snapshot", sa.String(length=128), nullable=False),
        sa.Column("resolved_model", sa.String(length=128), nullable=True),
        sa.Column("prompt_version", sa.String(length=64), nullable=False),
        sa.Column(
            "config_snapshot_sha256",
            sa.String(length=64, collation="utf8mb4_0900_bin"),
            nullable=False,
        ),
        sa.Column("request_id", sa.String(length=256), nullable=True),
        sa.Column("input_tokens", sa.Integer(), nullable=False),
        sa.Column("output_tokens", sa.Integer(), nullable=False),
        sa.Column("total_tokens", sa.Integer(), nullable=False),
        sa.Column("latency_ms", sa.Integer(), nullable=False),
        sa.Column("request_artifact_storage_backend", sa.String(length=16), nullable=False),
        sa.Column("request_artifact_location", sa.String(length=32), nullable=False),
        sa.Column(
            "request_artifact_bucket",
            sa.String(length=255, collation="utf8mb4_0900_bin"),
            nullable=False,
        ),
        sa.Column(
            "request_artifact_key",
            sa.String(length=1024, collation="utf8mb4_0900_bin"),
            nullable=False,
        ),
        sa.Column(
            "request_artifact_provider_version_id",
            sa.String(length=256, collation="utf8mb4_0900_bin"),
            nullable=False,
        ),
        sa.Column(
            "request_artifact_etag",
            sa.String(length=512, collation="utf8mb4_0900_bin"),
            nullable=False,
        ),
        sa.Column(
            "request_artifact_sha256",
            sa.String(length=64, collation="utf8mb4_0900_bin"),
            nullable=False,
        ),
        sa.Column("request_artifact_byte_size", sa.Integer(), nullable=False),
        sa.Column("response_artifact_storage_backend", sa.String(length=16), nullable=True),
        sa.Column("response_artifact_location", sa.String(length=32), nullable=True),
        sa.Column(
            "response_artifact_bucket",
            sa.String(length=255, collation="utf8mb4_0900_bin"),
            nullable=True,
        ),
        sa.Column(
            "response_artifact_key",
            sa.String(length=1024, collation="utf8mb4_0900_bin"),
            nullable=True,
        ),
        sa.Column(
            "response_artifact_provider_version_id",
            sa.String(length=256, collation="utf8mb4_0900_bin"),
            nullable=True,
        ),
        sa.Column(
            "response_artifact_etag",
            sa.String(length=512, collation="utf8mb4_0900_bin"),
            nullable=True,
        ),
        sa.Column(
            "response_artifact_sha256",
            sa.String(length=64, collation="utf8mb4_0900_bin"),
            nullable=True,
        ),
        sa.Column("response_artifact_byte_size", sa.Integer(), nullable=True),
        sa.Column("error_code", sa.String(length=128), nullable=True),
        sa.Column("error_category", sa.String(length=64), nullable=True),
        sa.Column("error_retryable", sa.Boolean(), nullable=True),
        sa.Column("retention_class", sa.String(length=16), nullable=False),
        sa.Column("retention_deadline", mysql.DATETIME(fsp=6), nullable=True),
        sa.Column("created_at", mysql.DATETIME(fsp=6), nullable=False),
        sa.CheckConstraint(
            "(retention_class = 'TASK' AND retention_deadline IS NOT NULL) "
            "OR (retention_class = 'FOUNDATION' AND retention_deadline IS NULL)",
            name="ck_product_brief_provider_calls_retention",
        ),
        sa.CheckConstraint(
            "config_snapshot_sha256 REGEXP '^[0-9a-f]{64}$'",
            name="ck_product_brief_provider_calls_config_snapshot",
        ),
        sa.CheckConstraint(
            "status IN ('SUCCEEDED', 'MALFORMED', 'THROTTLED', "
            "'TIMEOUT', 'UNAVAILABLE', 'REJECTED', 'UNKNOWN')",
            name="ck_product_brief_provider_calls_status",
        ),
        sa.CheckConstraint(
            "request_artifact_storage_backend IN ('MINIO', 'OSS') "
            "AND request_artifact_location = 'PROVIDER_RESULT' "
            "AND request_artifact_sha256 REGEXP '^[0-9a-f]{64}$' "
            "AND request_artifact_byte_size BETWEEN 0 AND 2097152",
            name="ck_pb_provider_calls_request_artifact",
        ),
        sa.CheckConstraint(
            "(response_artifact_storage_backend IS NULL "
            "AND response_artifact_location IS NULL "
            "AND response_artifact_bucket IS NULL "
            "AND response_artifact_key IS NULL "
            "AND response_artifact_provider_version_id IS NULL "
            "AND response_artifact_etag IS NULL "
            "AND response_artifact_sha256 IS NULL "
            "AND response_artifact_byte_size IS NULL) "
            "OR (response_artifact_storage_backend IS NOT NULL "
            "AND response_artifact_location IS NOT NULL "
            "AND response_artifact_bucket IS NOT NULL "
            "AND response_artifact_key IS NOT NULL "
            "AND response_artifact_provider_version_id IS NOT NULL "
            "AND response_artifact_etag IS NOT NULL "
            "AND response_artifact_sha256 IS NOT NULL "
            "AND response_artifact_byte_size IS NOT NULL)",
            name="ck_pb_provider_calls_response_presence",
        ),
        sa.CheckConstraint(
            "response_artifact_storage_backend IS NULL "
            "OR (response_artifact_storage_backend IN ('MINIO', 'OSS') "
            "AND response_artifact_location = 'PROVIDER_RESULT' "
            "AND response_artifact_sha256 REGEXP '^[0-9a-f]{64}$' "
            "AND response_artifact_byte_size BETWEEN 0 AND 2097152)",
            name="ck_pb_provider_calls_response_artifact",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "operation_id"],
            ["durable_operations.workspace_id", "durable_operations.id"],
            name="fk_product_brief_provider_calls_operation",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "product_brief_id"],
            ["product_briefs.workspace_id", "product_briefs.id"],
            name="fk_product_brief_provider_calls_brief",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "operation_id",
            "operation_attempt",
            "call_index",
            name="uq_product_brief_provider_calls_attempt",
        ),
        sa.UniqueConstraint(
            "workspace_id", "id", name="uq_product_brief_provider_calls_workspace_id"
        ),
        sa.UniqueConstraint(
            "workspace_id",
            "id",
            "product_brief_id",
            name="uq_product_brief_provider_calls_workspace_brief",
        ),
        mysql_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_index(
        "ix_product_brief_provider_calls_brief_created",
        "product_brief_provider_calls",
        ["workspace_id", "product_brief_id", "created_at", "id"],
        unique=False,
    )
    op.create_table(
        "product_brief_versions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("workspace_id", _WORKSPACE, nullable=False),
        sa.Column("product_brief_id", sa.String(length=36), nullable=False),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column("supersedes_version_id", sa.String(length=36), nullable=True),
        sa.Column("category", sa.String(length=32), nullable=False),
        sa.Column("common_schema_version", sa.String(length=64), nullable=False),
        sa.Column("category_schema_version", sa.String(length=64), nullable=False),
        sa.Column(
            "payload_sha256", sa.String(length=64, collation="utf8mb4_0900_bin"), nullable=False
        ),
        sa.Column("changed_paths_json", sa.JSON(), nullable=False),
        sa.Column("confirmation_required", sa.Boolean(), nullable=False),
        sa.Column("unresolved_field_count", sa.Integer(), nullable=False),
        sa.Column("review_policy_version", sa.String(length=64), nullable=False),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.Column("prompt_version", sa.String(length=64), nullable=True),
        sa.Column("provider_call_id", sa.String(length=36), nullable=True),
        sa.Column("actor_id", sa.String(length=128), nullable=False),
        sa.Column("revision_reason", sa.String(length=512), nullable=True),
        sa.Column("retention_class", sa.String(length=16), nullable=False),
        sa.Column("retention_deadline", mysql.DATETIME(fsp=6), nullable=True),
        sa.Column("created_at", mysql.DATETIME(fsp=6), nullable=False),
        sa.CheckConstraint(
            "(retention_class = 'TASK' AND retention_deadline IS NOT NULL) "
            "OR (retention_class = 'FOUNDATION' AND retention_deadline IS NULL)",
            name="ck_product_brief_versions_retention",
        ),
        sa.CheckConstraint(
            "(source = 'MODEL' AND prompt_version IS NOT NULL "
            "AND provider_call_id IS NOT NULL AND revision_reason IS NULL) "
            "OR (source = 'HUMAN' AND prompt_version IS NULL "
            "AND provider_call_id IS NULL AND revision_reason IS NOT NULL)",
            name="ck_product_brief_versions_provenance",
        ),
        sa.CheckConstraint(
            "category IN ('BEAUTY', 'AUTOMOTIVE')", name="ck_product_brief_versions_category"
        ),
        sa.CheckConstraint(
            "payload_sha256 REGEXP '^[0-9a-f]{64}$'",
            name="ck_product_brief_versions_payload_sha256",
        ),
        sa.CheckConstraint(
            "JSON_LENGTH(changed_paths_json) > 0",
            name="ck_product_brief_versions_changed_paths",
        ),
        sa.CheckConstraint("version_number > 0", name="ck_product_brief_versions_number"),
        sa.ForeignKeyConstraint(
            ["workspace_id", "product_brief_id"],
            ["product_briefs.workspace_id", "product_briefs.id"],
            name="fk_product_brief_versions_brief",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "provider_call_id", "product_brief_id"],
            [
                "product_brief_provider_calls.workspace_id",
                "product_brief_provider_calls.id",
                "product_brief_provider_calls.product_brief_id",
            ],
            name="fk_product_brief_versions_provider_call",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "supersedes_version_id", "product_brief_id"],
            [
                "product_brief_versions.workspace_id",
                "product_brief_versions.id",
                "product_brief_versions.product_brief_id",
            ],
            name="fk_product_brief_versions_supersedes",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "product_brief_id", "version_number", name="uq_product_brief_versions_number"
        ),
        sa.UniqueConstraint(
            "workspace_id",
            "id",
            "product_brief_id",
            name="uq_product_brief_versions_workspace_brief",
        ),
        sa.UniqueConstraint(
            "workspace_id",
            "id",
            "product_brief_id",
            "version_number",
            name="uq_product_brief_versions_exact",
        ),
        sa.UniqueConstraint("workspace_id", "id", name="uq_product_brief_versions_workspace_id"),
        mysql_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_index(
        "ix_product_brief_versions_history",
        "product_brief_versions",
        ["workspace_id", "product_brief_id", "version_number"],
        unique=False,
    )
    op.create_foreign_key(
        "fk_product_briefs_current_version",
        "product_briefs",
        "product_brief_versions",
        ["workspace_id", "current_version_id", "id"],
        ["workspace_id", "id", "product_brief_id"],
        ondelete="RESTRICT",
    )
    op.create_foreign_key(
        "fk_product_briefs_confirmed_version",
        "product_briefs",
        "product_brief_versions",
        ["workspace_id", "confirmed_version_id", "id"],
        ["workspace_id", "id", "product_brief_id"],
        ondelete="RESTRICT",
    )
    op.create_unique_constraint(
        "uq_workflow_approvals_confirmation_subject",
        "workflow_approvals",
        [
            "id",
            "workflow_id",
            "subject_id",
            "subject_version",
            "approval_type",
            "decision",
        ],
    )
    op.create_table(
        "product_brief_confirmations",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("workspace_id", _WORKSPACE, nullable=False),
        sa.Column("product_brief_id", sa.String(length=36), nullable=False),
        sa.Column("product_brief_version_id", sa.String(length=36), nullable=False),
        sa.Column("product_brief_version_number", sa.Integer(), nullable=False),
        sa.Column("workflow_id", sa.String(length=36), nullable=False),
        sa.Column("operation_id", sa.String(length=36), nullable=False),
        sa.Column("approval_id", sa.String(length=36), nullable=False),
        sa.Column("approval_type", sa.String(length=32), nullable=False),
        sa.Column("approval_decision", sa.String(length=24), nullable=False),
        sa.Column("confirmed_by", sa.String(length=128), nullable=False),
        sa.Column("reason_code", sa.String(length=128), nullable=True),
        sa.Column("comment_ref", sa.String(length=512), nullable=True),
        sa.Column("expected_product_brief_version", sa.Integer(), nullable=False),
        sa.Column("expected_workflow_version", sa.Integer(), nullable=False),
        sa.Column("created_at", mysql.DATETIME(fsp=6), nullable=False),
        sa.ForeignKeyConstraint(
            [
                "approval_id",
                "workflow_id",
                "product_brief_version_id",
                "product_brief_version_number",
                "approval_type",
                "approval_decision",
            ],
            [
                "workflow_approvals.id",
                "workflow_approvals.workflow_id",
                "workflow_approvals.subject_id",
                "workflow_approvals.subject_version",
                "workflow_approvals.approval_type",
                "workflow_approvals.decision",
            ],
            name="fk_product_brief_confirmations_approval_subject",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "operation_id"],
            ["durable_operations.workspace_id", "durable_operations.id"],
            name="fk_product_brief_confirmations_operation",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "product_brief_id"],
            ["product_briefs.workspace_id", "product_briefs.id"],
            name="fk_product_brief_confirmations_brief",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            [
                "workspace_id",
                "product_brief_version_id",
                "product_brief_id",
                "product_brief_version_number",
            ],
            [
                "product_brief_versions.workspace_id",
                "product_brief_versions.id",
                "product_brief_versions.product_brief_id",
                "product_brief_versions.version_number",
            ],
            name="fk_product_brief_confirmations_version",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "workflow_id"],
            ["workflows.workspace_id", "workflows.id"],
            name="fk_product_brief_confirmations_workflow",
            ondelete="RESTRICT",
        ),
        sa.CheckConstraint(
            "approval_type = 'PRODUCT_BRIEF'",
            name="ck_product_brief_confirmations_approval_type",
        ),
        sa.CheckConstraint(
            "approval_decision = 'APPROVE'",
            name="ck_product_brief_confirmations_approval_decision",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "product_brief_id",
            "product_brief_version_id",
            name="uq_product_brief_confirmations_exact_version",
        ),
        sa.UniqueConstraint(
            "approval_id",
            name="uq_product_brief_confirmations_approval",
        ),
        sa.UniqueConstraint(
            "workspace_id", "id", name="uq_product_brief_confirmations_workspace_id"
        ),
        mysql_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_index(
        "ix_product_brief_confirmations_history",
        "product_brief_confirmations",
        ["workspace_id", "product_brief_id", "created_at", "id"],
        unique=False,
    )
    op.create_table(
        "product_brief_fields",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("workspace_id", _WORKSPACE, nullable=False),
        sa.Column("product_brief_id", sa.String(length=36), nullable=False),
        sa.Column("product_brief_version_id", sa.String(length=36), nullable=False),
        sa.Column("path", sa.String(length=160), nullable=False),
        sa.Column("value_json", sa.JSON(), nullable=False),
        sa.Column("confidence", sa.Numeric(precision=5, scale=4), nullable=False),
        sa.Column("source", sa.String(length=24), nullable=False),
        sa.Column("conflict", sa.String(length=24), nullable=False),
        sa.Column("review_required", sa.Boolean(), nullable=False),
        sa.Column("sensitive", sa.Boolean(), nullable=False),
        sa.Column("review_reasons_json", sa.JSON(), nullable=False),
        sa.Column("created_at", mysql.DATETIME(fsp=6), nullable=False),
        sa.CheckConstraint(
            "conflict IN ('NONE', 'CONFLICTING', 'RESOLVED')",
            name="ck_product_brief_fields_conflict",
        ),
        sa.CheckConstraint(
            "source IN ('MODEL', 'HUMAN', 'PRODUCT_DATA')", name="ck_product_brief_fields_source"
        ),
        sa.CheckConstraint(
            "confidence >= 0 AND confidence <= 1", name="ck_product_brief_fields_confidence"
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "product_brief_version_id", "product_brief_id"],
            [
                "product_brief_versions.workspace_id",
                "product_brief_versions.id",
                "product_brief_versions.product_brief_id",
            ],
            name="fk_product_brief_fields_version",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "product_brief_version_id", "path", name="uq_product_brief_fields_path"
        ),
        sa.UniqueConstraint(
            "workspace_id",
            "id",
            "product_brief_version_id",
            "product_brief_id",
            name="uq_product_brief_fields_version",
        ),
        mysql_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_index(
        "ix_product_brief_fields_review",
        "product_brief_fields",
        ["workspace_id", "product_brief_id", "review_required", "sensitive"],
        unique=False,
    )
    op.create_table(
        "product_brief_source_assets",
        sa.Column("workspace_id", _WORKSPACE, nullable=False),
        sa.Column("analysis_request_id", sa.String(length=36), nullable=False),
        sa.Column("asset_id", sa.String(length=36), nullable=False),
        sa.Column("asset_version_id", sa.String(length=36), nullable=False),
        sa.Column("asset_object_id", sa.String(length=36), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("created_at", mysql.DATETIME(fsp=6), nullable=False),
        sa.CheckConstraint("ordinal >= 0 AND ordinal < 8", name="ck_product_brief_source_ordinal"),
        sa.ForeignKeyConstraint(
            ["workspace_id", "analysis_request_id"],
            ["product_brief_analysis_requests.workspace_id", "product_brief_analysis_requests.id"],
            name="fk_product_brief_source_assets_request",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "asset_object_id", "asset_version_id"],
            ["asset_objects.workspace_id", "asset_objects.id", "asset_objects.asset_version_id"],
            name="fk_product_brief_source_assets_object",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "asset_version_id", "asset_id"],
            ["asset_versions.workspace_id", "asset_versions.id", "asset_versions.asset_id"],
            name="fk_product_brief_source_assets_version",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint(
            "analysis_request_id", "asset_version_id", name="pk_product_brief_source_assets"
        ),
        sa.UniqueConstraint(
            "analysis_request_id", "ordinal", name="uq_product_brief_source_assets_ordinal"
        ),
        mysql_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_index(
        "ix_product_brief_source_assets_version",
        "product_brief_source_assets",
        ["workspace_id", "asset_version_id"],
        unique=False,
    )
    op.create_table(
        "product_brief_evidence",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("workspace_id", _WORKSPACE, nullable=False),
        sa.Column("product_brief_id", sa.String(length=36), nullable=False),
        sa.Column("product_brief_version_id", sa.String(length=36), nullable=False),
        sa.Column("field_id", sa.String(length=36), nullable=False),
        sa.Column("source_asset_version_id", sa.String(length=36), nullable=False),
        sa.Column("kind", sa.String(length=24), nullable=False),
        sa.Column("reference", sa.String(length=512), nullable=False),
        sa.Column("region_json", sa.JSON(), nullable=True),
        sa.Column(
            "excerpt_sha256", sa.String(length=64, collation="utf8mb4_0900_bin"), nullable=True
        ),
        sa.Column("created_at", mysql.DATETIME(fsp=6), nullable=False),
        sa.CheckConstraint(
            "excerpt_sha256 IS NULL OR excerpt_sha256 REGEXP '^[0-9a-f]{64}$'",
            name="ck_product_brief_evidence_excerpt_sha256",
        ),
        sa.CheckConstraint(
            "kind IN ('IMAGE_REGION', 'VISIBLE_TEXT', 'PRODUCT_DATA', 'HUMAN_NOTE')",
            name="ck_product_brief_evidence_kind",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "field_id", "product_brief_version_id", "product_brief_id"],
            [
                "product_brief_fields.workspace_id",
                "product_brief_fields.id",
                "product_brief_fields.product_brief_version_id",
                "product_brief_fields.product_brief_id",
            ],
            name="fk_product_brief_evidence_field",
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id", "source_asset_version_id"],
            ["asset_versions.workspace_id", "asset_versions.id"],
            name="fk_product_brief_evidence_source_version",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("workspace_id", "id", name="uq_product_brief_evidence_workspace_id"),
        mysql_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_index(
        "ix_product_brief_evidence_source",
        "product_brief_evidence",
        ["workspace_id", "source_asset_version_id", "created_at"],
        unique=False,
    )
    for table_name in _IMMUTABLE_HISTORY_TABLES:
        op.execute(
            sa.text(
                f"CREATE TRIGGER trg_{table_name}_no_update "
                f"BEFORE UPDATE ON {table_name} FOR EACH ROW "
                "SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = "
                f"'{table_name} are immutable'"
            )
        )
    for table_name in _DELETE_PROTECTED_TABLES:
        op.execute(
            sa.text(
                f"CREATE TRIGGER trg_{table_name}_no_delete "
                f"BEFORE DELETE ON {table_name} FOR EACH ROW "
                "SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = "
                f"'{table_name} cannot be deleted'"
            )
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert the schema change."""
    # ### commands auto generated by Alembic - please adjust! ###
    connection = op.get_bind()
    existing = sum(
        connection.execute(sa.text(f"SELECT COUNT(*) FROM {table_name}")).scalar_one()
        for table_name in _DELETE_PROTECTED_TABLES
    )
    if existing:
        raise RuntimeError("cannot downgrade while immutable ProductBrief history exists")
    for table_name in reversed(_DELETE_PROTECTED_TABLES):
        op.execute(sa.text(f"DROP TRIGGER IF EXISTS trg_{table_name}_no_delete"))
    for table_name in reversed(_IMMUTABLE_HISTORY_TABLES):
        op.execute(sa.text(f"DROP TRIGGER IF EXISTS trg_{table_name}_no_update"))
    op.drop_table("product_brief_evidence")
    op.drop_table("product_brief_source_assets")
    op.drop_table("product_brief_fields")
    op.drop_table("product_brief_confirmations")
    op.drop_constraint(
        "uq_workflow_approvals_confirmation_subject",
        "workflow_approvals",
        type_="unique",
    )
    op.drop_constraint(
        "fk_product_briefs_confirmed_version",
        "product_briefs",
        type_="foreignkey",
    )
    op.drop_constraint(
        "fk_product_briefs_current_version",
        "product_briefs",
        type_="foreignkey",
    )
    op.drop_table("product_brief_versions")
    op.drop_table("product_brief_provider_calls")
    op.drop_table("product_brief_provider_attempts")
    op.drop_table("product_brief_analysis_requests")
    op.drop_table("product_briefs")
    # ### end Alembic commands ###
