"""Generate the catalog TypeScript types from the committed OpenAPI document."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

SCHEMAS = (
    "CatalogDeleteRequestV1",
    "ErrorResponse",
    "ProductCreateRequestV1",
    "ProductListResponseV1",
    "ProductResponseV1",
    "ProductSummaryResponseV1",
    "ProductUpdateRequestV1",
    "SKUCreateRequestV1",
    "SKUResponseV1",
    "SKUUpdateRequestV1",
)


def schema_type(schema: dict[str, Any]) -> str:
    if "$ref" in schema:
        return schema["$ref"].rsplit("/", 1)[-1]
    if "enum" in schema:
        return " | ".join(json.dumps(value) for value in schema["enum"])
    if "anyOf" in schema:
        return " | ".join(schema_type(item) for item in schema["anyOf"])
    if schema.get("type") == "array":
        return f"Array<{schema_type(schema['items'])}>"
    if schema.get("type") == "object":
        if "additionalProperties" in schema:
            return "Record<string, unknown>"
        return "Record<string, unknown>"
    return {
        "boolean": "boolean",
        "integer": "number",
        "number": "number",
        "null": "null",
        "string": "string",
    }.get(schema.get("type", ""), "unknown")


def generate(document: dict[str, Any]) -> str:
    schemas = document["components"]["schemas"]
    lines = [
        "// Generated by scripts/generate_web_types.py. Do not edit by hand.",
        "",
    ]
    for name in SCHEMAS:
        schema = schemas[name]
        if "enum" in schema:
            lines.append(f"export type {name} = {schema_type(schema)};")
            lines.append("")
            continue
        lines.append(f"export interface {name} {{")
        required = set(schema.get("required", []))
        for property_name, property_schema in schema.get("properties", {}).items():
            optional = "" if property_name in required else "?"
            lines.append(f"  {property_name}{optional}: {schema_type(property_schema)};")
        lines.append("}")
        lines.append("")
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    root = Path(__file__).parents[1]
    source = root / "docs" / "api" / "openapi.json"
    target = root / "apps" / "web" / "lib" / "generated" / "catalog-api.ts"
    content = generate(json.loads(source.read_text(encoding="utf-8")))
    if args.check:
        if target.read_text(encoding="utf-8") != content:
            raise SystemExit("generated Web API types are out of date")
        print(target)
        return
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(content, encoding="utf-8")
    print(target)


if __name__ == "__main__":
    main()
